package com.xcs.phase2.dao.arrest;

import com.xcs.phase2.constant.Pattern;
import com.xcs.phase2.model.arrest.ArrestSearchWarrant;
import com.xcs.phase2.request.arrest.ArrestSearchWarrantgetByConAdvReq;
import com.xcs.phase2.request.arrest.ArrestSearchWarrantgetByKeywordReq;
import com.xcs.phase2.request.arrest.ArrestSearchWarrantupdByConReq;
import com.xcs.phase2.request.arrest.ArrestSearchWarrantupdDeleteReq;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;


@Service
@Transactional
public class ArrestSearchWarrantDAOImpl extends ArrestExt implements ArrestSearchWarrantDAO{
	
	private static final Logger log = LoggerFactory.getLogger(ArrestSearchWarrantDAOImpl.class);

	@Override
	public List<ArrestSearchWarrant> ArrestSearchWarrantgetByKeyword(ArrestSearchWarrantgetByKeywordReq req) {

		String str = "";

		if(req.getACCOUNT_OFFICE_CODE() != null && !"".equals(req.getACCOUNT_OFFICE_CODE()) && !"00".equals(req.getACCOUNT_OFFICE_CODE())) {

			if(req.getACCOUNT_OFFICE_CODE().length() == 6) {

				if("00".equals(req.getACCOUNT_OFFICE_CODE().substring(0, 2))) {
					str = " ";
				}else if("0000".equals(req.getACCOUNT_OFFICE_CODE().substring(2, 6))) {
					str = " AND ( " +
							" SUBSTR(OPS_SEARCH_WARRANT_STAFF.OPERATION_OFFICE_CODE,1,2) = SUBSTR('"+req.getACCOUNT_OFFICE_CODE()+"',1,2) " +
							"  OR SUBSTR(OPS_SEARCH_WARRANT_STAFF.MANAGEMENT_OFFICE_CODE,1,2) = SUBSTR('"+req.getACCOUNT_OFFICE_CODE()+"',1,2) " +
							"  OR SUBSTR(OPS_SEARCH_WARRANT_STAFF.REPRESENT_OFFICE_CODE,1,2) = SUBSTR('"+req.getACCOUNT_OFFICE_CODE()+"',1,2) " +
							" ) "  ;
				}else if("00".equals(req.getACCOUNT_OFFICE_CODE().substring(4, 6))) {
					str = " AND ( " +
							"  SUBSTR(OPS_SEARCH_WARRANT_STAFF.OPERATION_OFFICE_CODE,1,4) = SUBSTR('"+req.getACCOUNT_OFFICE_CODE()+"',1,4) " +
							"  OR SUBSTR(OPS_SEARCH_WARRANT_STAFF.MANAGEMENT_OFFICE_CODE,1,4) = SUBSTR('"+req.getACCOUNT_OFFICE_CODE()+"',1,4) " +
							"  OR SUBSTR(OPS_SEARCH_WARRANT_STAFF.REPRESENT_OFFICE_CODE,1,4) = SUBSTR('"+req.getACCOUNT_OFFICE_CODE()+"',1,4) " +
							" ) "  ;
				}else {
					str = " AND OPS_SEARCH_WARRANT_STAFF.OPERATION_OFFICE_CODE = '"+req.getACCOUNT_OFFICE_CODE()+"' ";
				}

			}

		}

		StringBuilder sqlBuilder = new StringBuilder()
			    .append("select " +
			    		"OPS_SEARCH_WARRANT.SEARCH_WARRANT_ID," +
			    		"OPS_SEARCH_WARRANT.ARREST_ID," +
			    		"OPS_SEARCH_WARRANT_REQUEST.REQUEST_CODE," +
			    		"OPS_SEARCH_WARRANT_REQUEST.REQUEST_NO," +
			    		"to_char(OPS_SEARCH_WARRANT_REQUEST.REQUEST_NO_YEAR,'"+ Pattern.FORMAT_DATETIME+"') as REQUEST_NO_YEAR," +
			    		"to_char(OPS_SEARCH_WARRANT_REQUEST.REQUEST_DATE,'"+Pattern.FORMAT_DATETIME+"') as REQUEST_DATE," +
			    		"OPS_SEARCH_WARRANT_STAFF.TITLE_NAME_TH as STAFF_TITLE_NAME_TH," +
			    		"OPS_SEARCH_WARRANT_STAFF.TITLE_NAME_EN as STAFF_TITLE_NAME_EN ," +
			    		"OPS_SEARCH_WARRANT_STAFF.TITLE_SHORT_NAME_TH as STAFF_TITLE_SHORT_NAME_TH," +
			    		"OPS_SEARCH_WARRANT_STAFF.TITLE_SHORT_NAME_EN as STAFF_TITLE_SHORT_NAME_EN," +
			    		"OPS_SEARCH_WARRANT_STAFF.FIRST_NAME as STAFF_FIRST_NAME ," +
			    		"OPS_SEARCH_WARRANT_STAFF.LAST_NAME as STAFF_LAST_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.OPERATION_OFFICE_NAME as STAFF_OPERATION_OFFICE_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.OPERATION_OFFICE_SHORT_NAME as STAFF_OPERATION_OFFICE_SHORT_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.OPREATION_POS_NAME as STAFF_OPREATION_POS_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.MANAGEMENT_OFFICE_NAME as STAFF_MANAGEMENT_OFFICE_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.MANAGEMENT_OFFICE_SHORT_NAME as STAFF_MANAGEMENT_OFFICE_SHORT_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.MANAGEMENT_POS_NAME as STAFF_MANAGEMENT_POS_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.REPRESENT_OFFICE_NAME as STAFF_REPRESENT_OFFICE_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.REPRESENT_OFFICE_SHORT_NAME as STAFF_REPRESENT_OFFICE_SHORT_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.REPRESENT_POS_NAME as STAFF_REPRESENT_POS_NAME," +

						"OPS_SEARCH_WARRANT_STAFF.OPERATION_OFFICE_CODE as OPERATION_OFFICE_CODE," +
						"OPS_SEARCH_WARRANT_STAFF.MANAGEMENT_OFFICE_CODE as MANAGEMENT_OFFICE_CODE," +
						"OPS_SEARCH_WARRANT_STAFF.REPRESENT_OFFICE_CODE as REPRESENT_OFFICE_CODE," +

						"OPS_SEARCH_WARRANT_REQUEST.REQUEST_DATE_FROM," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PRESENT_COURT_NAME," +
			    		"OPS_SEARCH_WARRANT_REQUEST.JUDGE_TITLE_NAME_TH," +
			    		"OPS_SEARCH_WARRANT_REQUEST.JUDGE_TITLE_NAME_EN," +
			    		"OPS_SEARCH_WARRANT_REQUEST.JUDGE_TITLE_SHORT_NAME_TH," +
			    		"OPS_SEARCH_WARRANT_REQUEST.JUDGE_TITLE_SHORT_NAME_EN," +
			    		"OPS_SEARCH_WARRANT_REQUEST.JUDGE_FIRST_NAME," +
			    		"OPS_SEARCH_WARRANT_REQUEST.JUDGE_LAST_NAME," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PERSON_TITLE_NAME_TH," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PERSON_TITLE_NAME_EN," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PERSON_TITLE_SHORT_NAME_TH," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PERSON_TITLE_SHORT_NAME_EN," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PERSON_FIRST_NAME," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PERSON_MIDDLE_NAME," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PERSON_LAST_NAME," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PERSON_OTHER_NAME," +
			    		"SW_SUB_DISTRICT.SUB_DISTRICT_NAME_TH," +
			    		"SW_SUB_DISTRICT.SUB_DISTRICT_NAME_EN," +
			    		"SW_DISTRICT.DISTRICT_NAME_TH," +
			    		"SW_DISTRICT.DISTRICT_NAME_EN," +
			    		"SW_PROVINCE.PROVINCE_NAME_TH," +
			    		"SW_PROVINCE.PROVINCE_NAME_EN," +
			    		"OPS_SEARCH_WARRANT.SEARCH_WARRANT_NO," +
						"to_char(OPS_SEARCH_WARRANT.SEARCH_WARRANT_NO_YEAR,'"+Pattern.FORMAT_DATETIME+"') as SEARCH_WARRANT_NO_YEAR," +
						"to_char(OPS_SEARCH_WARRANT.SEARCH_WARRANT_DATE,'"+Pattern.FORMAT_DATETIME+"') as SEARCH_WARRANT_DATE," +
						"OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_UNDECIDE_NO," +
			    		"to_char(OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_UNDECIDE_NO_YEAR,'"+Pattern.FORMAT_DATETIME+"') as CONSIDER_UNDECIDE_NO_YEAR," +
			    		"OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_DECIDE_NO," +
						"to_char(OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_DECIDE_NO_YEAR,'"+Pattern.FORMAT_DATETIME+"') as CONSIDER_DECIDE_NO_YEAR," +
						"to_char(OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_DATE,'"+Pattern.FORMAT_DATETIME+"') as CONSIDER_DATE" +
			    		" from OPS_SEARCH_WARRANT")
			    .append(" INNER JOIN OPS_SEARCH_WARRANT_CONSIDER ON OPS_SEARCH_WARRANT.CONSIDER_ID = OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_ID" +
			    		" INNER JOIN OPS_SEARCH_WARRANT_REQUEST ON OPS_SEARCH_WARRANT_CONSIDER.REQUEST_ID = OPS_SEARCH_WARRANT_REQUEST.REQUEST_ID" +
			    		" INNER JOIN OPS_SEARCH_WARRANT_STAFF ON OPS_SEARCH_WARRANT_REQUEST.REQUEST_ID = OPS_SEARCH_WARRANT_STAFF.REQUEST_ID" +
			    		" INNER JOIN MAS_SUB_DISTRICT SW_SUB_DISTRICT ON OPS_SEARCH_WARRANT_REQUEST.SUB_DISTRICT_ID = SW_SUB_DISTRICT.SUB_DISTRICT_ID" +
			    		" INNER JOIN MAS_DISTRICT SW_DISTRICT ON SW_SUB_DISTRICT.DISTRICT_ID = SW_DISTRICT.DISTRICT_ID" +
			    		" INNER JOIN MAS_PROVINCE SW_PROVINCE ON SW_DISTRICT.PROVINCE_ID = SW_PROVINCE.PROVINCE_ID" +
			    		" WHERE OPS_SEARCH_WARRANT.IS_ACTIVE = 1" +
			    		" AND OPS_SEARCH_WARRANT_STAFF.IS_ACTIVE = 1" +
			    		" AND OPS_SEARCH_WARRANT_STAFF.CONTRIBUTOR_ID = 1" +
			    		" AND OPS_SEARCH_WARRANT.IS_ARREST = 0" +
			    		" AND" +
			    		" (" +
			    		"  LOWER(OPS_SEARCH_WARRANT_REQUEST.REQUEST_CODE) LIKE LOWER(REPLACE('%"+req.getTEXT_SEARCH()+"%',' ',''))" +
			    		"  OR LOWER(OPS_SEARCH_WARRANT_REQUEST.PRESENT_COURT_NAME) LIKE LOWER(REPLACE('%"+req.getTEXT_SEARCH()+"%',' ',''))" +
			    		"  OR LOWER(OPS_SEARCH_WARRANT_REQUEST.PERSON_TITLE_NAME_TH||OPS_SEARCH_WARRANT_REQUEST.PERSON_FIRST_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_MIDDLE_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_LAST_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_OTHER_NAME) LIKE LOWER(REPLACE('%"+req.getTEXT_SEARCH()+"%',' ',''))" +
			    		"  OR LOWER(OPS_SEARCH_WARRANT_REQUEST.PERSON_TITLE_NAME_EN||OPS_SEARCH_WARRANT_REQUEST.PERSON_FIRST_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_MIDDLE_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_LAST_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_OTHER_NAME) LIKE LOWER(REPLACE('%"+req.getTEXT_SEARCH()+"%',' ',''))" +
			    		"  OR LOWER(OPS_SEARCH_WARRANT_REQUEST.PERSON_TITLE_SHORT_NAME_TH||OPS_SEARCH_WARRANT_REQUEST.PERSON_FIRST_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_MIDDLE_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_LAST_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_OTHER_NAME) LIKE LOWER(REPLACE('%"+req.getTEXT_SEARCH()+"%',' ',''))" +
			    		"  OR LOWER(OPS_SEARCH_WARRANT_REQUEST.PERSON_TITLE_SHORT_NAME_EN||OPS_SEARCH_WARRANT_REQUEST.PERSON_FIRST_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_MIDDLE_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_LAST_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_OTHER_NAME) LIKE LOWER(REPLACE('%"+req.getTEXT_SEARCH()+"%',' ',''))  " +
			    		"  OR LOWER(OPS_SEARCH_WARRANT_STAFF.TITLE_NAME_TH||OPS_SEARCH_WARRANT_STAFF.FIRST_NAME||OPS_SEARCH_WARRANT_STAFF.LAST_NAME) LIKE LOWER(REPLACE('%"+req.getTEXT_SEARCH()+"%',' ',''))" +
			    		"  OR LOWER(OPS_SEARCH_WARRANT_STAFF.TITLE_NAME_EN||OPS_SEARCH_WARRANT_STAFF.FIRST_NAME||OPS_SEARCH_WARRANT_STAFF.LAST_NAME) LIKE LOWER(REPLACE('%"+req.getTEXT_SEARCH()+"%',' ',''))" +
			    		"  OR LOWER(OPS_SEARCH_WARRANT_STAFF.TITLE_SHORT_NAME_TH||OPS_SEARCH_WARRANT_STAFF.FIRST_NAME||OPS_SEARCH_WARRANT_STAFF.LAST_NAME) LIKE LOWER(REPLACE('%"+req.getTEXT_SEARCH()+"%',' ',''))" +
			    		"  OR LOWER(OPS_SEARCH_WARRANT_STAFF.TITLE_SHORT_NAME_EN||OPS_SEARCH_WARRANT_STAFF.FIRST_NAME||OPS_SEARCH_WARRANT_STAFF.LAST_NAME) LIKE LOWER(REPLACE('%"+req.getTEXT_SEARCH()+"%',' ',''))" +
			    		" )" +str+
			    		" ORDER BY OPS_SEARCH_WARRANT_REQUEST.REQUEST_CODE DESC");

		log.info("[SQL]  : " + sqlBuilder.toString());

		@SuppressWarnings("unchecked")
		List<ArrestSearchWarrant> dataList = getJdbcTemplate().query(sqlBuilder.toString(), new RowMapper() {

			public ArrestSearchWarrant mapRow(ResultSet rs, int rowNum) throws SQLException {
				ArrestSearchWarrant item = new ArrestSearchWarrant();
				item.setSEARCH_WARRANT_ID(rs.getInt("SEARCH_WARRANT_ID"));
				item.setARREST_ID(rs.getInt("ARREST_ID"));
				item.setREQUEST_CODE(rs.getString("REQUEST_CODE"));
				item.setREQUEST_NO(rs.getString("REQUEST_NO"));
				item.setREQUEST_NO_YEAR(rs.getString("REQUEST_NO_YEAR"));
				item.setREQUEST_DATE(rs.getString("REQUEST_DATE"));
				item.setSTAFF_TITLE_NAME_TH(rs.getString("STAFF_TITLE_NAME_TH"));
				item.setSTAFF_TITLE_NAME_EN(rs.getString("STAFF_TITLE_NAME_EN"));
				item.setSTAFF_TITLE_SHORT_NAME_TH(rs.getString("STAFF_TITLE_SHORT_NAME_TH"));
				item.setSTAFF_TITLE_SHORT_NAME_EN(rs.getString("STAFF_TITLE_SHORT_NAME_EN"));
				item.setSTAFF_FIRST_NAME(rs.getString("STAFF_FIRST_NAME"));
				item.setSTAFF_LAST_NAME(rs.getString("STAFF_LAST_NAME"));
				item.setSTAFF_OPERATION_OFFICE_NAME(rs.getString("STAFF_OPERATION_OFFICE_NAME"));
				item.setSTAFF_OPERATION_OFFICE_SHORT_NAME(rs.getString("STAFF_OPERATION_OFFICE_SHORT_NAME"));
				item.setSTAFF_OPREATION_POS_NAME(rs.getString("STAFF_OPREATION_POS_NAME"));
				item.setSTAFF_MANAGEMENT_OFFICE_NAME(rs.getString("STAFF_MANAGEMENT_OFFICE_NAME"));
				item.setSTAFF_MANAGEMENT_OFFICE_SHORT_NAME(rs.getString("STAFF_MANAGEMENT_OFFICE_SHORT_NAME"));
				item.setSTAFF_MANAGEMENT_POS_NAME(rs.getString("STAFF_MANAGEMENT_POS_NAME"));
				item.setSTAFF_REPRESENT_OFFICE_NAME(rs.getString("STAFF_REPRESENT_OFFICE_NAME"));
				item.setSTAFF_REPRESENT_OFFICE_SHORT_NAME(rs.getString("STAFF_REPRESENT_OFFICE_SHORT_NAME"));
				item.setSTAFF_REPRESENT_POS_NAME(rs.getString("STAFF_REPRESENT_POS_NAME"));
				item.setREQUEST_DATE_FROM(rs.getString("REQUEST_DATE_FROM"));
				item.setPRESENT_COURT_NAME(rs.getString("PRESENT_COURT_NAME"));
				item.setJUDGE_TITLE_NAME_TH(rs.getString("JUDGE_TITLE_NAME_TH"));
				item.setJUDGE_TITLE_NAME_EN(rs.getString("JUDGE_TITLE_NAME_EN"));
				item.setJUDGE_TITLE_SHORT_NAME_TH(rs.getString("JUDGE_TITLE_SHORT_NAME_TH"));
				item.setJUDGE_TITLE_SHORT_NAME_EN(rs.getString("JUDGE_TITLE_SHORT_NAME_EN"));
				item.setJUDGE_FIRST_NAME(rs.getString("JUDGE_FIRST_NAME"));
				item.setJUDGE_LAST_NAME(rs.getString("JUDGE_LAST_NAME"));
				item.setPERSON_TITLE_NAME_TH(rs.getString("PERSON_TITLE_NAME_TH"));
				item.setPERSON_TITLE_NAME_EN(rs.getString("PERSON_TITLE_NAME_EN"));
				item.setPERSON_TITLE_SHORT_NAME_TH(rs.getString("PERSON_TITLE_SHORT_NAME_TH"));
				item.setPERSON_TITLE_SHORT_NAME_EN(rs.getString("PERSON_TITLE_SHORT_NAME_EN"));
				item.setPERSON_FIRST_NAME(rs.getString("PERSON_FIRST_NAME"));
				item.setPERSON_MIDDLE_NAME(rs.getString("PERSON_MIDDLE_NAME"));
				item.setPERSON_LAST_NAME(rs.getString("PERSON_LAST_NAME"));
				item.setPERSON_OTHER_NAME(rs.getString("PERSON_OTHER_NAME"));
				item.setSUB_DISTRICT_NAME_TH(rs.getString("SUB_DISTRICT_NAME_TH"));
				item.setSUB_DISTRICT_NAME_EN(rs.getString("SUB_DISTRICT_NAME_EN"));
				item.setDISTRICT_NAME_TH(rs.getString("DISTRICT_NAME_TH"));
				item.setDISTRICT_NAME_EN(rs.getString("DISTRICT_NAME_EN"));
				item.setPROVINCE_NAME_TH(rs.getString("PROVINCE_NAME_TH"));
				item.setPROVINCE_NAME_EN(rs.getString("PROVINCE_NAME_EN"));
				item.setSEARCH_WARRANT_NO(rs.getInt("SEARCH_WARRANT_NO"));
				item.setSEARCH_WARRANT_NO_YEAR(rs.getString("SEARCH_WARRANT_NO_YEAR"));
				item.setSEARCH_WARRANT_DATE(rs.getString("SEARCH_WARRANT_DATE"));
				item.setCONSIDER_UNDECIDE_NO(rs.getInt("CONSIDER_UNDECIDE_NO"));
				item.setCONSIDER_UNDECIDE_NO_YEAR(rs.getString("CONSIDER_UNDECIDE_NO_YEAR"));
				item.setCONSIDER_DECIDE_NO(rs.getInt("CONSIDER_DECIDE_NO"));
				item.setCONSIDER_DECIDE_NO_YEAR(rs.getString("CONSIDER_DECIDE_NO_YEAR"));
				item.setCONSIDER_DATE(rs.getString("CONSIDER_DATE"));

				item.setOPERATION_OFFICE_CODE(rs.getString("OPERATION_OFFICE_CODE"));
				item.setMANAGEMENT_OFFICE_CODE(rs.getString("MANAGEMENT_OFFICE_CODE"));
				item.setREPRESENT_OFFICE_CODE(rs.getString("REPRESENT_OFFICE_CODE"));
				return item;
			}
		});

		return dataList;

	}

	@Override
	public List<ArrestSearchWarrant> ArrestSearchWarrantgetByConAdv(ArrestSearchWarrantgetByConAdvReq req) {
		
		String tempRequestDateFrom  = "";
		String tempRequestDateTo = "";
		String tempConsiderDateFrom  = "";
		String tempConsiderDateTo = "";
		String tempSearchWarrantDateFrom  = "";
		String tempSearchWarrantDateTo = "";
        String str = "";

        if(req.getACCOUNT_OFFICE_CODE() != null && !"".equals(req.getACCOUNT_OFFICE_CODE()) && !"00".equals(req.getACCOUNT_OFFICE_CODE())) {

            if(req.getACCOUNT_OFFICE_CODE().length() == 6) {

				if("00".equals(req.getACCOUNT_OFFICE_CODE().substring(0, 2))) {
					str = " ";
				}else if("0000".equals(req.getACCOUNT_OFFICE_CODE().substring(2, 6))) {
					str = " AND ( " +
							" SUBSTR(OPS_SEARCH_WARRANT_STAFF.OPERATION_OFFICE_CODE,1,2) = SUBSTR('"+req.getACCOUNT_OFFICE_CODE()+"',1,2) " +
							"  OR SUBSTR(OPS_SEARCH_WARRANT_STAFF.MANAGEMENT_OFFICE_CODE,1,2) = SUBSTR('"+req.getACCOUNT_OFFICE_CODE()+"',1,2) " +
							"  OR SUBSTR(OPS_SEARCH_WARRANT_STAFF.REPRESENT_OFFICE_CODE,1,2) = SUBSTR('"+req.getACCOUNT_OFFICE_CODE()+"',1,2) " +
							" ) "  ;
				}else if("00".equals(req.getACCOUNT_OFFICE_CODE().substring(4, 6))) {
					str = " AND ( " +
							"  SUBSTR(OPS_SEARCH_WARRANT_STAFF.OPERATION_OFFICE_CODE,1,4) = SUBSTR('"+req.getACCOUNT_OFFICE_CODE()+"',1,4) " +
							"  OR SUBSTR(OPS_SEARCH_WARRANT_STAFF.MANAGEMENT_OFFICE_CODE,1,4) = SUBSTR('"+req.getACCOUNT_OFFICE_CODE()+"',1,4) " +
							"  OR SUBSTR(OPS_SEARCH_WARRANT_STAFF.REPRESENT_OFFICE_CODE,1,4) = SUBSTR('"+req.getACCOUNT_OFFICE_CODE()+"',1,4) " +
							" ) "  ;
				}else {
					str = " AND OPS_SEARCH_WARRANT_STAFF.OPERATION_OFFICE_CODE = '"+req.getACCOUNT_OFFICE_CODE()+"' ";
				}

            }

        }
		 
		 if(!"".equals(req.getREQUEST_DATE_FROM())) {
			 tempRequestDateFrom = String.format("%s %s", req.getREQUEST_DATE_FROM(),Pattern.TIME_FROM);
		 }
		 
		 if(!"".equals(req.getREQUEST_DATE_TO())) {
			 tempRequestDateTo = String.format("%s %s", req.getREQUEST_DATE_TO(),Pattern.TIME_TO);
		 }
		 
			 if(!"".equals(req.getCONSIDER_DATE_FROM())) {
				 tempConsiderDateFrom = String.format("%s %s", req.getCONSIDER_DATE_FROM(),Pattern.TIME_FROM);
			 }
			 
			 if(!"".equals(req.getCONSIDER_DATE_TO())) {
				 tempRequestDateTo = String.format("%s %s", req.getCONSIDER_DATE_TO(),Pattern.TIME_TO);
			 }
			 
				 if(!"".equals(req.getSEARCH_WARRANT_DATE_FROM())) {
					 tempSearchWarrantDateFrom = String.format("%s %s", req.getSEARCH_WARRANT_DATE_FROM(),Pattern.TIME_FROM);
				 }
				 
				 if(!"".equals(req.getSEARCH_WARRANT_DATE_TO())) {
					 tempSearchWarrantDateTo = String.format("%s %s", req.getSEARCH_WARRANT_DATE_TO(),Pattern.TIME_TO);
				 }

		StringBuilder sqlBuilder = new StringBuilder()
			    .append("select " +
			    		"OPS_SEARCH_WARRANT.SEARCH_WARRANT_ID," +
			    		"OPS_SEARCH_WARRANT.ARREST_ID," +
			    		"OPS_SEARCH_WARRANT_REQUEST.REQUEST_CODE," +
			    		"OPS_SEARCH_WARRANT_REQUEST.REQUEST_NO," +
			    		"to_char(OPS_SEARCH_WARRANT_REQUEST.REQUEST_NO_YEAR,'"+Pattern.FORMAT_DATETIME+"') as REQUEST_NO_YEAR," +
			    		"to_char(OPS_SEARCH_WARRANT_REQUEST.REQUEST_DATE,'"+Pattern.FORMAT_DATETIME+"') as REQUEST_DATE," +
			    		"OPS_SEARCH_WARRANT_STAFF.TITLE_NAME_TH as STAFF_TITLE_NAME_TH," +
			    		"OPS_SEARCH_WARRANT_STAFF.TITLE_NAME_EN as STAFF_TITLE_NAME_EN ," +
			    		"OPS_SEARCH_WARRANT_STAFF.TITLE_SHORT_NAME_TH as STAFF_TITLE_SHORT_NAME_TH," +
			    		"OPS_SEARCH_WARRANT_STAFF.TITLE_SHORT_NAME_EN as STAFF_TITLE_SHORT_NAME_EN," +
			    		"OPS_SEARCH_WARRANT_STAFF.FIRST_NAME as STAFF_FIRST_NAME ," +
			    		"OPS_SEARCH_WARRANT_STAFF.LAST_NAME as STAFF_LAST_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.OPERATION_OFFICE_NAME as STAFF_OPERATION_OFFICE_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.OPERATION_OFFICE_SHORT_NAME as STAFF_OPERATION_OFFICE_SHORT_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.OPREATION_POS_NAME as STAFF_OPREATION_POS_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.MANAGEMENT_OFFICE_NAME as STAFF_MANAGEMENT_OFFICE_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.MANAGEMENT_OFFICE_SHORT_NAME as STAFF_MANAGEMENT_OFFICE_SHORT_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.MANAGEMENT_POS_NAME as STAFF_MANAGEMENT_POS_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.REPRESENT_OFFICE_NAME as STAFF_REPRESENT_OFFICE_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.REPRESENT_OFFICE_SHORT_NAME as STAFF_REPRESENT_OFFICE_SHORT_NAME," +
			    		"OPS_SEARCH_WARRANT_STAFF.REPRESENT_POS_NAME as STAFF_REPRESENT_POS_NAME," +
						"OPS_SEARCH_WARRANT_STAFF.OPERATION_OFFICE_CODE as OPERATION_OFFICE_CODE," +
						"OPS_SEARCH_WARRANT_STAFF.MANAGEMENT_OFFICE_CODE as MANAGEMENT_OFFICE_CODE," +
						"OPS_SEARCH_WARRANT_STAFF.REPRESENT_OFFICE_CODE as REPRESENT_OFFICE_CODE," +
			    		"OPS_SEARCH_WARRANT_REQUEST.REQUEST_DATE_FROM," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PRESENT_COURT_NAME," +
			    		"OPS_SEARCH_WARRANT_REQUEST.JUDGE_TITLE_NAME_TH," +
			    		"OPS_SEARCH_WARRANT_REQUEST.JUDGE_TITLE_NAME_EN," +
			    		"OPS_SEARCH_WARRANT_REQUEST.JUDGE_TITLE_SHORT_NAME_TH," +
			    		"OPS_SEARCH_WARRANT_REQUEST.JUDGE_TITLE_SHORT_NAME_EN," +
			    		"OPS_SEARCH_WARRANT_REQUEST.JUDGE_FIRST_NAME," +
			    		"OPS_SEARCH_WARRANT_REQUEST.JUDGE_LAST_NAME," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PERSON_TITLE_NAME_TH," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PERSON_TITLE_NAME_EN," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PERSON_TITLE_SHORT_NAME_TH," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PERSON_TITLE_SHORT_NAME_EN," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PERSON_FIRST_NAME," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PERSON_MIDDLE_NAME," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PERSON_LAST_NAME," +
			    		"OPS_SEARCH_WARRANT_REQUEST.PERSON_OTHER_NAME," +
			    		"SW_SUB_DISTRICT.SUB_DISTRICT_NAME_TH," +
			    		"SW_SUB_DISTRICT.SUB_DISTRICT_NAME_EN," +
			    		"SW_DISTRICT.DISTRICT_NAME_TH," +
			    		"SW_DISTRICT.DISTRICT_NAME_EN," +
			    		"SW_PROVINCE.PROVINCE_NAME_TH," +
			    		"SW_PROVINCE.PROVINCE_NAME_EN," +
			    		"OPS_SEARCH_WARRANT.SEARCH_WARRANT_NO," +
						"to_char(OPS_SEARCH_WARRANT.SEARCH_WARRANT_NO_YEAR,'"+Pattern.FORMAT_DATETIME+"') as SEARCH_WARRANT_NO_YEAR," +
						"to_char(OPS_SEARCH_WARRANT.SEARCH_WARRANT_DATE,'"+Pattern.FORMAT_DATETIME+"') as SEARCH_WARRANT_DATE," +
						"OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_UNDECIDE_NO," +
			    		"to_char(OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_UNDECIDE_NO_YEAR,'"+Pattern.FORMAT_DATETIME+"') as CONSIDER_UNDECIDE_NO_YEAR," +
			    		"OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_DECIDE_NO," +
						"to_char(OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_DECIDE_NO_YEAR,'"+Pattern.FORMAT_DATETIME+"') as CONSIDER_DECIDE_NO_YEAR," +
						"to_char(OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_DATE,'"+Pattern.FORMAT_DATETIME+"') as CONSIDER_DATE" +
			    		" from OPS_SEARCH_WARRANT")
			    .append(" INNER JOIN OPS_SEARCH_WARRANT_CONSIDER ON OPS_SEARCH_WARRANT.CONSIDER_ID = OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_ID" +
			    		" INNER JOIN OPS_SEARCH_WARRANT_REQUEST ON OPS_SEARCH_WARRANT_CONSIDER.REQUEST_ID = OPS_SEARCH_WARRANT_REQUEST.REQUEST_ID" +
			    		" INNER JOIN OPS_SEARCH_WARRANT_STAFF ON OPS_SEARCH_WARRANT_REQUEST.REQUEST_ID = OPS_SEARCH_WARRANT_STAFF.REQUEST_ID" +
			    		" INNER JOIN MAS_SUB_DISTRICT SW_SUB_DISTRICT ON OPS_SEARCH_WARRANT_REQUEST.SUB_DISTRICT_ID = SW_SUB_DISTRICT.SUB_DISTRICT_ID" +
			    		" INNER JOIN MAS_DISTRICT SW_DISTRICT ON SW_SUB_DISTRICT.DISTRICT_ID = SW_DISTRICT.DISTRICT_ID" +
			    		" INNER JOIN MAS_PROVINCE SW_PROVINCE ON SW_DISTRICT.PROVINCE_ID = SW_PROVINCE.PROVINCE_ID" +
			    		" WHERE OPS_SEARCH_WARRANT.IS_ACTIVE = 1" +
			    		" AND OPS_SEARCH_WARRANT_STAFF.IS_ACTIVE = 1" +
			    		" AND OPS_SEARCH_WARRANT_STAFF.CONTRIBUTOR_ID = 1" +
			    		" AND OPS_SEARCH_WARRANT.IS_ARREST = 0");

		if(req.getREQUEST_CODE() != null && !"".equals(req.getREQUEST_CODE())) {
			sqlBuilder.append(" AND LOWER(OPS_SEARCH_WARRANT_REQUEST.REQUEST_CODE) LIKE LOWER(REPLACE('%"+req.getREQUEST_CODE()+"%',' ','')) ");
		}
		
		if(req.getREQUEST_NO() != null && !"".equals(req.getREQUEST_NO())) {
			sqlBuilder.append(" AND LOWER(OPS_SEARCH_WARRANT_REQUEST.REQUEST_NO) LIKE LOWER(REPLACE('%"+req.getREQUEST_NO()+"%',' ','')) ");
		}
		
		if(req.getREQUEST_NO_YEAR() != null && !"".equals(req.getREQUEST_NO_YEAR())) {
			sqlBuilder.append(" AND (to_number(TO_CHAR(OPS_SEARCH_WARRANT_REQUEST.REQUEST_NO_YEAR,'YYYY', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI')) >= '"+req.getREQUEST_NO_YEAR()+"' AND to_number(TO_CHAR(OPS_SEARCH_WARRANT_REQUEST.REQUEST_NO_YEAR,'YYYY', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI')) <='"+req.getREQUEST_NO_YEAR()+"') ");
		}
		
		if(req.getCOURT_NAME() != null && !"".equals(req.getCOURT_NAME())) {
			sqlBuilder.append(" AND LOWER(OPS_SEARCH_WARRANT_REQUEST.PRESENT_COURT_NAME) LIKE LOWER(REPLACE('%"+req.getCOURT_NAME()+"%',' ','')) ");
		}
		
		if(req.getREQUEST_DATE_FROM() != null && !"".equals(req.getREQUEST_DATE_FROM()) && req.getREQUEST_DATE_TO() != null && !"".equals(req.getREQUEST_DATE_TO())) {
			sqlBuilder.append(" AND OPS_SEARCH_WARRANT_REQUEST.REQUEST_DATE BETWEEN  to_date(nvl('"+tempRequestDateFrom+"','0001-01-01 00:00'),'YYYY-MM-DD HH24:MI') and to_date(nvl('"+tempRequestDateTo+"','9999-12-31 23:59'),'YYYY-MM-DD HH24:MI')");
		}
		
		if(req.getPERSON_NAME() != null && !"".equals(req.getPERSON_NAME())) {
			sqlBuilder.append(" AND " +
					"( " +
					"  LOWER(OPS_SEARCH_WARRANT_REQUEST.PERSON_TITLE_NAME_TH||OPS_SEARCH_WARRANT_REQUEST.PERSON_FIRST_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_MIDDLE_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_LAST_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_OTHER_NAME) LIKE LOWER(REPLACE('%"+req.getPERSON_NAME()+"%',' ',''))" +
					"  OR LOWER(OPS_SEARCH_WARRANT_REQUEST.PERSON_TITLE_NAME_EN||OPS_SEARCH_WARRANT_REQUEST.PERSON_FIRST_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_MIDDLE_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_LAST_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_OTHER_NAME) LIKE LOWER(REPLACE('%"+req.getPERSON_NAME()+"%',' ',''))" +
					"  OR LOWER(OPS_SEARCH_WARRANT_REQUEST.PERSON_TITLE_SHORT_NAME_TH||OPS_SEARCH_WARRANT_REQUEST.PERSON_FIRST_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_MIDDLE_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_LAST_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_OTHER_NAME) LIKE LOWER(REPLACE('%"+req.getPERSON_NAME()+"%',' ',''))" +
					"  OR LOWER(OPS_SEARCH_WARRANT_REQUEST.PERSON_TITLE_SHORT_NAME_EN||OPS_SEARCH_WARRANT_REQUEST.PERSON_FIRST_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_MIDDLE_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_LAST_NAME||OPS_SEARCH_WARRANT_REQUEST.PERSON_OTHER_NAME) LIKE LOWER(REPLACE('%"+req.getPERSON_NAME()+"%',' ',''))  " +
					" )");
		}
		
		if(req.getSTAFF_NAME() != null && !"".equals(req.getSTAFF_NAME())) {
			sqlBuilder.append(" AND " +
					"(" +
					"  LOWER(OPS_SEARCH_WARRANT_STAFF.TITLE_NAME_TH||OPS_SEARCH_WARRANT_STAFF.FIRST_NAME||OPS_SEARCH_WARRANT_STAFF.LAST_NAME) LIKE LOWER(REPLACE('%"+req.getSTAFF_NAME()+"%',' ',''))" +
					"  OR LOWER(OPS_SEARCH_WARRANT_STAFF.TITLE_NAME_EN||OPS_SEARCH_WARRANT_STAFF.FIRST_NAME||OPS_SEARCH_WARRANT_STAFF.LAST_NAME) LIKE LOWER(REPLACE('%"+req.getSTAFF_NAME()+"%',' ',''))" +
					"  OR LOWER(OPS_SEARCH_WARRANT_STAFF.TITLE_SHORT_NAME_TH||OPS_SEARCH_WARRANT_STAFF.FIRST_NAME||OPS_SEARCH_WARRANT_STAFF.LAST_NAME) LIKE LOWER(REPLACE('%"+req.getSTAFF_NAME()+"%',' ',''))" +
					"  OR LOWER(OPS_SEARCH_WARRANT_STAFF.TITLE_SHORT_NAME_EN||OPS_SEARCH_WARRANT_STAFF.FIRST_NAME||OPS_SEARCH_WARRANT_STAFF.LAST_NAME) LIKE LOWER(REPLACE('%"+req.getSTAFF_NAME()+"%',' ',''))" +
					" )");
		}
		
		if(req.getCONSIDER_UNDECIDE_NO() != null && !"".equals(req.getCONSIDER_UNDECIDE_NO())) {
			sqlBuilder.append(" AND LOWER(OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_UNDECIDE_NO) LIKE LOWER(REPLACE('%"+req.getCONSIDER_UNDECIDE_NO()+"%',' ','')) ");
		}
		
		if(req.getCONSIDER_UNDECIDE_NO_YEAR() != null && !"".equals(req.getCONSIDER_UNDECIDE_NO_YEAR())) {
			sqlBuilder.append(" AND (to_number(TO_CHAR(OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_UNDECIDE_NO_YEAR,'YYYY', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI')) >= '"+req.getCONSIDER_UNDECIDE_NO_YEAR()+"' AND to_number(TO_CHAR(OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_UNDECIDE_NO_YEAR,'YYYY', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI')) <='"+req.getCONSIDER_UNDECIDE_NO_YEAR()+"') ");
		}
		
		if(req.getCONSIDER_DECIDE_NO() != null && !"".equals(req.getCONSIDER_DECIDE_NO())) {
			sqlBuilder.append(" AND LOWER(OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_DECIDE_NO) LIKE LOWER(REPLACE('%"+req.getCONSIDER_DECIDE_NO()+"%',' ','')) ");
		}
		
		if(req.getCONSIDER_DECIDE_NO_YEAR() != null && !"".equals(req.getCONSIDER_DECIDE_NO_YEAR())) {
			sqlBuilder.append(" AND (to_number(TO_CHAR(OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_DECIDE_NO_YEAR,'YYYY', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI')) >= '"+req.getCONSIDER_DECIDE_NO_YEAR()+"' AND to_number(TO_CHAR(OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_DECIDE_NO_YEAR,'YYYY', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI')) <='"+req.getCONSIDER_DECIDE_NO_YEAR()+"') ");
		}
		
		if(req.getCONSIDER_DATE_FROM() != null && !"".equals(req.getCONSIDER_DATE_FROM()) && req.getCONSIDER_DATE_TO() != null && !"".equals(req.getCONSIDER_DATE_TO())) {
			sqlBuilder.append(" AND OPS_SEARCH_WARRANT_CONSIDER.CONSIDER_DATE BETWEEN  to_date(nvl('"+tempConsiderDateFrom+"','0001-01-01 00:00'),'YYYY-MM-DD HH24:MI') and to_date(nvl('"+tempConsiderDateTo+"','9999-12-31 23:59'),'YYYY-MM-DD HH24:MI')");
		}
		
		if(req.getSEARCH_WARRANT_NO() != null && !"".equals(req.getSEARCH_WARRANT_NO())) {
			sqlBuilder.append(" AND LOWER(OPS_SEARCH_WARRANT.SEARCH_WARRANT_NO) LIKE LOWER(REPLACE('%"+req.getSEARCH_WARRANT_NO()+"%',' ','')) ");
		}
		
		if(req.getSEARCH_WARRANT_NO_YEAR() != null && !"".equals(req.getSEARCH_WARRANT_NO_YEAR())) {
			sqlBuilder.append(" AND (to_number(TO_CHAR(OPS_SEARCH_WARRANT.SEARCH_WARRANT_NO_YEAR,'YYYY', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI')) >= '"+req.getSEARCH_WARRANT_NO_YEAR()+"' AND to_number(TO_CHAR(OPS_SEARCH_WARRANT.SEARCH_WARRANT_NO_YEAR,'YYYY', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI')) <='"+req.getSEARCH_WARRANT_NO_YEAR()+"') ");
		}
		
		if(req.getSEARCH_WARRANT_DATE_FROM() != null && !"".equals(req.getSEARCH_WARRANT_DATE_FROM()) && req.getSEARCH_WARRANT_DATE_TO() != null && !"".equals(req.getSEARCH_WARRANT_DATE_TO())) {
			sqlBuilder.append(" AND OPS_SEARCH_WARRANT.SEARCH_WARRANT_DATE BETWEEN  to_date(nvl('"+tempSearchWarrantDateFrom+"','0001-01-01 00:00'),'YYYY-MM-DD HH24:MI') and to_date(nvl('"+tempSearchWarrantDateTo+"','9999-12-31 23:59'),'YYYY-MM-DD HH24:MI')");
		}
		
		sqlBuilder.append(" "+str+" ORDER BY OPS_SEARCH_WARRANT_REQUEST.REQUEST_CODE DESC ");
		
		log.info("[SQL]  : " + sqlBuilder.toString());

		@SuppressWarnings("unchecked")
		List<ArrestSearchWarrant> dataList = getJdbcTemplate().query(sqlBuilder.toString(), new RowMapper() {

			public ArrestSearchWarrant mapRow(ResultSet rs, int rowNum) throws SQLException {
				ArrestSearchWarrant item = new ArrestSearchWarrant();
				item.setSEARCH_WARRANT_ID(rs.getInt("SEARCH_WARRANT_ID"));
				item.setARREST_ID(rs.getInt("ARREST_ID"));
				item.setREQUEST_CODE(rs.getString("REQUEST_CODE"));
				item.setREQUEST_NO(rs.getString("REQUEST_NO"));
				item.setREQUEST_NO_YEAR(rs.getString("REQUEST_NO_YEAR"));
				item.setREQUEST_DATE(rs.getString("REQUEST_DATE"));
				item.setSTAFF_TITLE_NAME_TH(rs.getString("STAFF_TITLE_NAME_TH"));
				item.setSTAFF_TITLE_NAME_EN(rs.getString("STAFF_TITLE_NAME_EN"));
				item.setSTAFF_TITLE_SHORT_NAME_TH(rs.getString("STAFF_TITLE_SHORT_NAME_TH"));
				item.setSTAFF_TITLE_SHORT_NAME_EN(rs.getString("STAFF_TITLE_SHORT_NAME_EN"));
				item.setSTAFF_FIRST_NAME(rs.getString("STAFF_FIRST_NAME"));
				item.setSTAFF_LAST_NAME(rs.getString("STAFF_LAST_NAME"));
				item.setSTAFF_OPERATION_OFFICE_NAME(rs.getString("STAFF_OPERATION_OFFICE_NAME"));
				item.setSTAFF_OPERATION_OFFICE_SHORT_NAME(rs.getString("STAFF_OPERATION_OFFICE_SHORT_NAME"));
				item.setSTAFF_OPREATION_POS_NAME(rs.getString("STAFF_OPREATION_POS_NAME"));
				item.setSTAFF_MANAGEMENT_OFFICE_NAME(rs.getString("STAFF_MANAGEMENT_OFFICE_NAME"));
				item.setSTAFF_MANAGEMENT_OFFICE_SHORT_NAME(rs.getString("STAFF_MANAGEMENT_OFFICE_SHORT_NAME"));
				item.setSTAFF_MANAGEMENT_POS_NAME(rs.getString("STAFF_MANAGEMENT_POS_NAME"));
				item.setSTAFF_REPRESENT_OFFICE_NAME(rs.getString("STAFF_REPRESENT_OFFICE_NAME"));
				item.setSTAFF_REPRESENT_OFFICE_SHORT_NAME(rs.getString("STAFF_REPRESENT_OFFICE_SHORT_NAME"));
				item.setSTAFF_REPRESENT_POS_NAME(rs.getString("STAFF_REPRESENT_POS_NAME"));
				item.setREQUEST_DATE_FROM(rs.getString("REQUEST_DATE_FROM"));
				item.setPRESENT_COURT_NAME(rs.getString("PRESENT_COURT_NAME"));
				item.setJUDGE_TITLE_NAME_TH(rs.getString("JUDGE_TITLE_NAME_TH"));
				item.setJUDGE_TITLE_NAME_EN(rs.getString("JUDGE_TITLE_NAME_EN"));
				item.setJUDGE_TITLE_SHORT_NAME_TH(rs.getString("JUDGE_TITLE_SHORT_NAME_TH"));
				item.setJUDGE_TITLE_SHORT_NAME_EN(rs.getString("JUDGE_TITLE_SHORT_NAME_EN"));
				item.setJUDGE_FIRST_NAME(rs.getString("JUDGE_FIRST_NAME"));
				item.setJUDGE_LAST_NAME(rs.getString("JUDGE_LAST_NAME"));
				item.setPERSON_TITLE_NAME_TH(rs.getString("PERSON_TITLE_NAME_TH"));
				item.setPERSON_TITLE_NAME_EN(rs.getString("PERSON_TITLE_NAME_EN"));
				item.setPERSON_TITLE_SHORT_NAME_TH(rs.getString("PERSON_TITLE_SHORT_NAME_TH"));
				item.setPERSON_TITLE_SHORT_NAME_EN(rs.getString("PERSON_TITLE_SHORT_NAME_EN"));
				item.setPERSON_FIRST_NAME(rs.getString("PERSON_FIRST_NAME"));
				item.setPERSON_MIDDLE_NAME(rs.getString("PERSON_MIDDLE_NAME"));
				item.setPERSON_LAST_NAME(rs.getString("PERSON_LAST_NAME"));
				item.setPERSON_OTHER_NAME(rs.getString("PERSON_OTHER_NAME"));
				item.setSUB_DISTRICT_NAME_TH(rs.getString("SUB_DISTRICT_NAME_TH"));
				item.setSUB_DISTRICT_NAME_EN(rs.getString("SUB_DISTRICT_NAME_EN"));
				item.setDISTRICT_NAME_TH(rs.getString("DISTRICT_NAME_TH"));
				item.setDISTRICT_NAME_EN(rs.getString("DISTRICT_NAME_EN"));
				item.setPROVINCE_NAME_TH(rs.getString("PROVINCE_NAME_TH"));
				item.setPROVINCE_NAME_EN(rs.getString("PROVINCE_NAME_EN"));
				item.setSEARCH_WARRANT_NO(rs.getInt("SEARCH_WARRANT_NO"));
				item.setSEARCH_WARRANT_NO_YEAR(rs.getString("SEARCH_WARRANT_NO_YEAR"));
				item.setSEARCH_WARRANT_DATE(rs.getString("SEARCH_WARRANT_DATE"));
				item.setCONSIDER_UNDECIDE_NO(rs.getInt("CONSIDER_UNDECIDE_NO"));
				item.setCONSIDER_UNDECIDE_NO_YEAR(rs.getString("CONSIDER_UNDECIDE_NO_YEAR"));
				item.setCONSIDER_DECIDE_NO(rs.getInt("CONSIDER_DECIDE_NO"));
				item.setCONSIDER_DECIDE_NO_YEAR(rs.getString("CONSIDER_DECIDE_NO_YEAR"));
				item.setCONSIDER_DATE(rs.getString("CONSIDER_DATE"));

				item.setOPERATION_OFFICE_CODE(rs.getString("OPERATION_OFFICE_CODE"));
				item.setMANAGEMENT_OFFICE_CODE(rs.getString("MANAGEMENT_OFFICE_CODE"));
				item.setREPRESENT_OFFICE_CODE(rs.getString("REPRESENT_OFFICE_CODE"));
				return item;
			}
		});

		return dataList;

	}

	@Override
	public Boolean ArrestSearchWarrantupdByCon(List<ArrestSearchWarrantupdByConReq> request) {

		if(request != null) {
	    	log.info("[Sub] Size : "+request.size());
	    	
		    if(request.size() > 0){
		    	
		    	for(ArrestSearchWarrantupdByConReq req : request){
		    		StringBuilder sqlBuilderSub = new StringBuilder()
		    				.append("UPDATE OPS_SEARCH_WARRANT "
		    						+ "SET "
		    						+"ARREST_ID = '"+req.getARREST_ID()+"',"
		    						+"IS_ARREST = '1' "
		    						+ "WHERE SEARCH_WARRANT_ID = '"+req.getSEARCH_WARRANT_ID()+"' ");
		    				log.info("[SQL] : "+sqlBuilderSub.toString());
		    				
		    		getJdbcTemplate().update(sqlBuilderSub.toString(), new Object[] {});
		    	}
		    }
	    }
		
		return true;
	}

	@Override
	public Boolean ArrestSearchWarrantupdDelete(List<ArrestSearchWarrantupdDeleteReq> request) {

		if(request != null) {
	    	log.info("[Sub] Size : "+request.size());
	    	
		    if(request.size() > 0){
		    	
		    	for(ArrestSearchWarrantupdDeleteReq req : request){
		    		StringBuilder sqlBuilderSub = new StringBuilder()
		    				.append("UPDATE OPS_SEARCH_WARRANT "
		    						+ "SET "
		    						+"ARREST_ID = '0',"
		    						+"IS_ARREST = '0' "
		    						+ "WHERE SEARCH_WARRANT_ID = '"+req.getSEARCH_WARRANT_ID()+"' ");
		    				log.info("[SQL] : "+sqlBuilderSub.toString());
		    				
		    		getJdbcTemplate().update(sqlBuilderSub.toString(), new Object[] {});
		    	}
		    }
	    }
		
		return true;
	}

}
